config/routes.rb
  post 'plan-mejoramiento-educativo/jeditable_nombre_pme_subdimensiones' => 'pme_parametros#jeditable_nombre_pme_subdimensiones', as: :jeditable_nombre_pme_subdimensiones
  get 'plan-mejoramiento-educativo/get_pme_subdimension' => 'pme_parametros#get_pme_subdimension', as: :get_pme_subdimension

  get 'plan-mejoramiento-educativo/get_pme_objetivo' => 'pme_objetivo_estrategia#get_pme_objetivo', as: :get_pme_objetivo
  get 'plan-mejoramiento-educativo/:est/objetivos' => 'pme_objetivo_estrategia#objetivos', as: :pme_objetivos
  get 'plan-mejoramiento-educativo/:est/nuevo_objetivo' => 'pme_objetivo_estrategia#nuevo_objetivo', as: :pme_nuevo_objetivo
  post 'plan-mejoramiento-educativo/:est/crear_objetivo' => 'pme_objetivo_estrategia#crear_objetivo', as: :pme_crear_objetivo
  post 'plan-mejoramiento-educativo/jeditable_nombre_pme_objetivo' => 'pme_objetivo_estrategia#jeditable_nombre_pme_objetivo', as: :jeditable_nombre_pme_objetivo
  post 'plan-mejoramiento-educativo/:id/destroy_pme_objetivo' => 'pme_objetivo_estrategia#destroy_pme_objetivo', as: :destroy_pme_objetivo
 
  get 'plan-mejoramiento-educativo/get_pme_estrategia' => 'pme_objetivo_estrategia#get_pme_estrategia', as: :get_pme_estrategia
  get 'plan-mejoramiento-educativo/:est/objetivo/:id/estrategia' => 'pme_objetivo_estrategia#estrategia_objetivo', as: :pme_estrategias_objetivo
  post 'plan-mejoramiento-educativo/:est/editar/:id/crear_estrategia' => 'pme_objetivo_estrategia#crear_estrategia', as: :pme_crear_estrategia
  post 'plan-mejoramiento-educativo/:est/eliminar/:id/estrategia' => 'pme_objetivo_estrategia#eliminar_estrategia', as: :pme_eliminar_estrategia
  post 'plan-mejoramiento-educativo/jeditable_nombre_pme_estrategia' => 'pme_objetivo_estrategia#jeditable_nombre_pme_estrategia', as: :jeditable_nombre_pme_estrategia
  post 'plan-mejoramiento-educativo/:id/destroy_pme_estrategia' => 'pme_objetivo_estrategia#destroy_pme_estrategia', as: :destroy_pme_estrategia

  get 'plan-mejoramiento-educativo/get_pme_accion' => 'pme_accion#get_pme_accion', as: :get_pme_accion
  get 'plan-mejoramiento-educativo/sl_pme_accion' => 'pme_accion#sl_pme_accion', as: :sl_pme_accion
  get 'plan-mejoramiento-educativo/:est/acciones' => 'pme_accion#index', as: :pme_acciones
  get 'plan-mejoramiento-educativo/:est/nueva' => 'pme_accion#nueva', as: :pme_nueva_accion
  post 'plan-mejoramiento-educativo/:est/crear' => 'pme_accion#crear', as: :pme_crear_accion
  get 'plan-mejoramiento-educativo/:est/ver/:id/accion' => 'pme_accion#ver', as: :pme_ver_accion
  post 'plan-mejoramiento-educativo/:est/editar/:id/accion' => 'pme_accion#editar', as: :pme_editar_accion
  post 'plan-mejoramiento-educativo/:est/eliminar/:id/accion' => 'pme_accion#eliminar', as: :pme_eliminar_accion

  get 'plan-mejoramiento-educativo/:est/ver/:id/accion/:act/actividad' => 'pme_actividad#ver', as: :pme_ver_actividad
  get 'plan-mejoramiento-educativo/:est/ver/:id/pme_nueva_actividad' => 'pme_actividad#nueva', as: :pme_nueva_actividad
  post 'plan-mejoramiento-educativo/:id/crea_actividad' => 'pme_actividad#crear', as: :pme_crea_actividad
  post 'plan-mejoramiento-educativo/:id/actualiza_actividad' => 'pme_actividad#actualiza', as: :pme_actualiza_actividad
  post 'plan-mejoramiento-educativo/:id/subir_pme_actividad_doc' => 'pme_actividad#subir_pme_actividad_doc', as: :subir_pme_actividad_doc

  get 'opi/nueva' => 'opi#nueva', as: :nueva_opi
  post 'opi/crear' => 'opi#crear', as: :crear_opi
  get 'opi/validar' => 'opi#validar', as: :validar_opi
  get 'opi/:id/ver' => 'opi#ver', as: :ver_opi
  post 'opi/:id/actualizar' => 'opi#actualizar', as: :actualiza_opi

  get 'gestionar/:id/opi' => 'gestionar#opi', as: :gestionar_opi
  post 'gestionar/:id/validar' => 'gestionar#validar', as: :gestionar_validar_opi
  post 'gestionar/:id/sigue_conducto' => 'gestionar#sigue_conducto', as: :sigue_conducto
  post 'gestionar/:id/responde_consulta' => 'gestionar#responde_consulta', as: :responde_consulta
  post 'gestionar/:id/rechazada' => 'gestionar#rechazada', as: :gestionar_rechazada
  post 'gestionar/:id/adquisicion' => 'gestionar#adquisicion', as: :gestionar_adquisicion
  post 'gestionar/:id/termina_decreto' => 'gestionar#termina_decreto', as: :termina_decreto

  get 'xml/' => 'xml#index', as: :xml

  get 'bandejas/' => 'bandeja#index', as: :bandejas
  get 'bandejas/mi-bandeja' => 'bandeja#mi_bandeja', as: :mi_bandeja
  get 'bandejas/asesor_subvencion' => 'bandeja#asesor_subvencion', as: :entrantes_asesor_subvencion
  get 'bandejas/encargado_subvencion' => 'bandeja#encargado_subvencion', as: :entrantes_encargado_subvencion
  get 'bandejas/:id/entrantes' => 'bandeja#entrantes', as: :bandeja_entrantes
  post 'bandejas/guardar' => 'bandeja#guarda', as: :guarda_bandeja
  get 'bandejas/:id/ver' => 'bandeja#ver', as: :ver_bandeja
  post 'bandejas/:id/guarda_usuario' => 'bandeja#guarda_usuario', as: :guarda_usuario_bandeja
  post 'bandejas/:id/elimina_usuario' => 'bandeja#elimina_usuario', as: :elimina_usuario_bandeja

  get 'conducto/' => 'conducto#index', as: :conducto
  post 'conducto/guardar' => 'conducto#guardar', as: :guarda_conducto

  get 'encargados-subvencion/' => 'encargado#encargados', as: :encargados_subvencion
  get 'asesores-subvencion/' => 'encargado#asesores', as: :asesores_subvencion
  post 'encargados-subvencion/guarda_encargado' => 'encargado#guarda_encargado', as: :guarda_encargado
  post 'asesores-subvencion/guarda_asesor' => 'encargado#guarda_asesor', as: :guarda_asesor
  post 'encargados-subvencion/:id/borra_asesor' => 'encargado#borra_asesor', as: :borra_asesor
  post 'asesores-subvencion/:id/borra_encargado' => 'encargado#borra_encargado', as: :borra_encargado

  get 'cuentas_gastos/' => 'cuenta_gastos#index', as: :cuentas_gastos
  post 'cuentas_gastos/guardar' => 'cuenta_gastos#guardar', as: :guarda_cuenta_gasto
  post 'cuentas_gastos/eliminar' => 'cuenta_gastos#eliminar', as: :eliminar_cuenta_gasto

  get 'usuarios/' => 'usuarios#index', as: :usuarios
  get 'usuarios/nuevo' => 'usuarios#nuevo', as: :nuevo_usuario
  get 'usuarios/bajas' => 'usuarios#bajas', as: :bajas_usuario
  post 'usuarios/guardar' => 'usuarios#guardar', as: :guardar_usuario
  get 'usuarios/:id/editar' => 'usuarios#editar', as: :editar_usuario
  get 'usuarios/:id/perfil' => 'usuarios#perfil', as: :perfil
  post 'usuarios/:id/actualizar' => 'usuarios#actualizar', as: :actualizar_usuario
  post 'usuarios/:id/actualizar_perfil' => 'usuarios#actualizar_perfil', as: :actualizar_perfil
  post 'usuarios/:id/actualiza_password' => 'usuarios#actualiza_password', as: :actualiza_password
  post 'usuarios/:id/baja' => 'usuarios#baja', as: :baja
  get 'usuarios/get_usuario' => 'usuarios#get_usuario', as: :get_usuario

    get 'establecimiento/' => 'establecimientos#index', as: :establecimientos
    get 'establecimiento/nuevo' => 'establecimientos#new', as: :nuevo_establecimiento
    post 'establecimiento/guardar' => 'establecimientos#create', as: :guardar_establecimiento
    get 'establecimiento/get_dpto' => 'establecimientos#get_dpto', as: :get_dpto
    get 'establecimiento/get_dpto_usuario' => 'establecimientos#get_dpto_usuario', as: :get_dpto_usuario
    get 'establecimiento/:id/ver' => 'establecimientos#show', as: :ver_establecimiento
    post 'establecimiento/:id/actualizar' => 'establecimientos#update', as: :actualizar_establecimiento
    post 'establecimiento/:id/eliminar' => 'establecimientos#eliminar_establecimiento', as: :eliminar_establecimiento
    

    get 'departamento/:id/ver' => 'establecimientos#departamento', as: :ver_departamento
    post 'departamento/:id/actualizar' => 'establecimientos#actualizar_departamento', as: :actualizar_departamento
    post 'departamento/:id/guardar' => 'establecimientos#guardar_departamento', as: :guardar_departamento
    post 'departamento/:id/eliminar' => 'establecimientos#eliminar_departamento', as: :eliminar_departamento

   

  match(
    "home/general" => "home#general",
    :as => :general,
    :via => :get
  )

  match(
    "home/:id/dashboard" => "home#dashboard",
    :as => :dashboard,
    :via => :get
  )

  match(
    "pagar/index" => "pagar#index",
    :as => :pagar,
    :via => :get
  )
   match(
    "pagar/todas_recepciones" => "pagar#todas_recepciones",
    :as => :todas_recepciones,
    :via => :get
  ) 
   match(
    "pagar/:id/ver" => "pagar#ver",
    :as => :ver_pagar,
    :via => :get
  )  
  match(
    "pagar/:id/quitar_lista_pagar" => "pagar#quitar_lista_pagar",
    :as => :quitar_lista_pagar,
    :via => :post
  )
   match(
    "pagar/:id/guarda_cheque" => "pagar#guarda_cheque",
    :as => :guarda_cheque,
    :via => :post
  ) 
  match(
    "informe/gastos-categoria" => "informe#gastos_categoria",
    :as => :gastos_categoria,
    :via => :get
  )
  match(
    "informe/informe_gastos_categoria" => "informe#informe_gastos_categoria",
    :as => :informe_gastos_categoria,
    :via => :get  )

  match(
    "informe/gastos-subvencion" => "informe#gastos_subvencion",
    :as => :gastos_subvencion,
    :via => :get
  )
   match(
    "informe/informe_gastos_subvencion" => "informe#informe_gastos_subvencion",
    :as => :informe_gastos_subvencion,
    :via => :get  )
  match(
    "informe/:id/gastos-subvencion" => "informe#ver_gastos_subvencion",
    :as => :ver_gastos_subvencion,
    :via => :get,
    :format => "pdf"
  )

  match(
    "informe/ingresos-subvencion" => "informe#ingresos_subvencion",
    :as => :ingresos_subvencion,
    :via => :get
  )
  match(
    "informe/:id/ingresos-subvencion" => "informe#ver_ingresos_subvencion",
    :as => :ver_ingresos_subvencion,
    :via => :get,
    :format => "pdf"
  )

  match(
    "informe/compras" => "informe#compras",
    :as => :informe_compras,
    :via => :get
  )
  match(
    "informe/informe_compras" => "informe#informe_compras",
    :as => :genera_informe_compras,
    :via => :get  )
  match(
    "informe/:id/ver-compras" => "informe#ver_compras",
    :as => :ver_informe_compras,
    :via => :get,
    :format => "pdf"
  )

app/helpers/opi_helper.rb
module OpiHelper
end

app/views/opi/gestionar.html.erb
<div class="row">
	<div class="col-lg-12">
		<ol class="breadcrumb">
		<li><a href="#">Inicio</a></li>
			<li class="active"><span>Gestionar OPI</span></li>
		</ol>
		<h1>Orden Periodo <%= @orden.periodo.anio %></h1>
	</div>
</div>



<div class="row" >
		<div class="col-md-12">
			<div class="row form-horizontal">
				<div class="col-lg-12">
					<div class="main-box">
						<header class="main-box-header clearfix">
							<h2>Ultimo Movimiento</h2>
						</header>
						<div class="main-box-body clearfix">
						<div class="form-group">
								<label  class="col-lg-2 control-label">Departamento</label>
								<div class="col-lg-10">
									<input type="text" readonly="" value="<%= @orden.movimientos.last.departamento.nombre %>"  class="form-control">  
									 
								</div>
							</div>
							<div class="form-group">
								<label  class="col-lg-2 control-label">Funcionario</label>
								<div class="col-lg-10">
									<input type="text" readonly="" value="<%= @orden.movimientos.last.usuario.nombre %> <%= @orden.movimientos.last.usuario.apaterno %>"  class="form-control">  
									 
								</div>
							</div>
							<div class="form-group">
								<label  class="col-lg-2 control-label">Estado</label>
								<div class="col-lg-10">
									<input type="text" readonly="" value="<%= @orden.movimientos.last.estado %>"  class="form-control">  
									 
								</div>
							</div>
							<div class="form-group">
								<label  class="col-lg-2 control-label">Comentario</label>
								<div class="col-lg-10">
									<textarea class="form-control" readonly=""> <%= @orden.movimientos.last.comentario %> </textarea> 
									 
								</div>
							</div>
						
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>


<%= render "opi/partial/show" %>



<script type="text/javascript"> 
// Funcion antes de enviarse
function showRequest2(formData, jqForm, options) { 


	var validator = $( "#new_orden" ).validate();
	if(validator.form()){
		return true;
	}else{
		alertify.error("Error, Por favor compruebe los campos señalados.");
		return false;

	}



} 

// Funcion despues de enviarse 
function showResponse2(responseText, statusText)  { 

  console.log(responseText);
  console.log(statusText);

  if(responseText.estado == "Exito"){

    $("#exito_producto").show("slow").fadeOut(6000);
    alertify.success("Se ha guardado el producto exitosamente");
    $("#cajas").html("")
    $("form")[0].reset();
  }else
   alertify.error("Error, no se ha guardado el producto, revise los campos ingresados");
}


	$(document).ready(function() {

		//Opciones jquery.forms
		    var options2 = { 
		        beforeSubmit:  showRequest2,  // Funcion a ejecutar antes de enviarse
		        success:       showResponse2,  //Funcion a ejecutar despues de enviarse
		        dataType:  'json' //tipo de dato a devolver
		      }; 


		      $(".gestion_opi_btn").click(function() {
			      $('#gestion_opi_form').ajaxSubmit(options2); 
		      })
		 	

		    
		    


	
		

	})
</script>

app/views/opi/nueva.html.erb
<div class="row">
	<div class="col-lg-12">
		<ol class="breadcrumb">
		<li><a href="#">Inicio</a></li>
			<li class="active"><span>Nueva OPI</span></li>
		</ol>
		<h1>Nueva OPI</h1>
	</div>
</div>

<% if @estado_sistema.activo || @usuario_actual.departamento.establecimiento.id == 1 %>

<form action="<%= crear_opi_path %>" class="new_orden " id="new_orden" method="post" onKeypress="if(event.keyCode == 13) event.returnValue = false;">

	<%= render "opi/partial/orden" %>

	<div id="bloque_area" style="display:none">
		<%= render "opi/partial/new_pme" %>
	</div>
	<%= render "opi/partial/presupuesto" %>
	<%= render "opi/partial/subvencion" %>


	
	<div  id="bloque_articulos" >
		<%= render "opi/partial/articulos" %>
	</div>

	<div id="doc_orden">
						
					</div>
</form>
<form accept-charset="UTF-8" action="<%= crear_documento_path %>" class="new_doc" id="new_doc" method="post" enctype="multipart/form-data">
	<div class="row" id="bloque_archivos">
		<div class="col-md-12">
		<%= render "opi/partial/archivo" %>
		</div>
	</div>
</form>
	<div class="form-actions text-center">
		<button type="button" id="crear_btn" class="btn btn-primary">Crear Orden</button>
		<button type="button" class="btn btn-default">Cancel</button>
	</div>


<script type="text/javascript">

// Funcion antes de enviarse
function showRequest2(formData, jqForm, options) { 

	$("#crear_btn").prop('disabled', true);
	$("#crear_btn").html('Enviando...');
	var validator = $( "#new_orden" ).validate();
	if(validator.form()){
		disponible = parseInt($("#p_disponible").val()) 
		solicitado = parseInt($("#solicitado").val())
		console.log("Disponible: " + disponible + "")
		console.log("Solicitado: " + solicitado + "")
		if(disponible < solicitado){
			alertify.alert("Lo sentimos, el monto solicitado excede al disponible");
			$("#crear_btn").prop('disabled', false);
			$("#crear_btn").html('Crear Orden');
			return false;
		}else{
			return true;
		}
	}else{
		alertify.error("Error, Por favor compruebe los campos señalados.");
		$("#crear_btn").prop('disabled', false);
		$("#crear_btn").html('Crear Orden');	
		return false;

	}




} 

// Funcion despues de enviarse 
function showResponse2(responseText, statusText)  { 

  console.log(responseText);
  console.log(statusText);

  if(responseText.estado == "Exito"){

    $("#exito_producto").show("slow").fadeOut(6000);
    alertify.alert("ORDEN ID: " + responseText.orden.id + "", function(){
     document.location.href = "/ordenes/enviadas"
  	});

   
  }else{
  $("#crear_btn").prop('disabled', false);
  $("#crear_btn").html('Crear Orden');
   alertify.error(responseText.estado);
	}
}


	$(document).ready(function() {


		//Opciones jquery.forms
		    var options2 = { 
		        beforeSubmit:  showRequest2,  // Funcion a ejecutar antes de enviarse
		        success:       showResponse2,  //Funcion a ejecutar despues de enviarse
		        dataType:  'json' //tipo de dato a devolver
		      }; 


		      $("#crear_btn").click(function() {
			      $('#new_orden').ajaxSubmit(options2); 
		      })
		 	

		    
		    


		$("#sl_subvencion").change(function(){
			$.getJSON("<%= get_subvencion_path %>", { id: $(this).val() }, function(data){
			if(data.es_sep){
				$("#bloque_area").show("slow");
			}else{
				$("#bloque_area").hide("slow");
				
			}
				$("#p_total").val(puntitos(parseInt(data.pagado)));
				$("#p_proceso").val(puntitos(parseInt(data.tramite)));
				$("#p_libre").val(puntitos(parseInt(data.restante)));
				$("#p_disponible").val(parseInt(data.restante));
			}) 
		})



	})
</script>

<% else %>

<p>Modulo de creación de nuevas OPI se encuentra temporalmente <b>CERRADO</b></p>
<% end %>

app/views/opi/validar.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="main-box clearfix">
      <header class="main-box-header clearfix">
        <h2 class="pull-left">Validar OPI Establecimiento</h2>
        <div class="filter-block pull-right">
          <div class="form-group pull-left">
           
          </div>

        </div>
      </header>
      <div class="main-box-body clearfix">
          
        
          <table class="table table-striped" id="datatable">
            <thead>
              <tr>
                <th>ID</th>
                <th class="text-center">Titulo</th>
                <th class="text-center">Origen</th>
                <th class="text-center">Subvención</th>
                <th class="text-center">Creada</th>
                <th>&nbsp;</th>
              </tr>
            </thead>
            <tbody>
              <% @validar.each do |o| %>
                <tr>
                  <td>
                    <%= o.id %>
                  </td>
                  <td class="text-left">
                    <%= o.titulo %>
                  </td>
                  <td class="text-left">
                    <%= o.departamento.nombre %> - <%= o.departamento.establecimiento.nombre %>
                  </td>
                  <td class="text-left">
                    <%= o.subcategoria_gasto.categoria_gasto.tipo_gasto.subvencion.nombre %>
                  </td>
                  <td class="text-left">
                    <%= o.created_at.strftime('%d/%m/%Y %H:%M') %>
                  </td>
                  <td style="width: 15%;">

                    <a href="<%= gestionar_opi_path o.id %>" class="table-link" data-toggle="tooltip" data-placement="top" title="Gestionar Orden">
                      <span class="fa-stack">
                        <i class="fa fa-square fa-stack-2x"></i>
                        <i class="fa fa-edit fa-stack-1x fa-inverse"></i>
                      </span>
                    </a>
               
                                

                  </td>      
                </tr>
              <% end %>
            </tbody>
          </table>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
$(document).ready(function() {
  $('#datatable').DataTable({
    "sDom": "R<'row-fluid'<'span6'l><'span6'f>r>t<'row-fluid'<'span6'i><'span6'p>>",
    responsive: true
  });


  $('[data-toggle="tooltip"]').tooltip()

})
</script>

app/views/opi/ver.html.erb
<div class="row">
	<div class="col-lg-12">
		<ol class="breadcrumb">
		<li><a href="#">Inicio</a></li>
			<li class="active"><span>Ver orden Pedido</span></li>
		</ol>
		<h1>Orden Periodo <%= @orden.periodo.anio %></h1>
	</div>
</div>



	<%= render "opi/partial/show" %>


<script type="text/javascript">

// Funcion antes de enviarse
function showRequest2(formData, jqForm, options) { 

	var validator = $( "#new_orden" ).validate();
	if(validator.form()){
		return true;
	}else{
		alertify.error("Error, Por favor compruebe los campos señalados.");
		return false;

	}



} 

// Funcion despues de enviarse 
function showResponse2(responseText, statusText)  { 

  console.log(responseText);
  console.log(statusText);

  if(responseText.estado == "Exito"){

    $("#exito_producto").show("slow").fadeOut(6000);
    alertify.success("Se ha guardado el producto exitosamente");
    $("#cajas").html("")
    $("form")[0].reset();
  }else
   alertify.error("Error, no se ha guardado el producto, revise los campos ingresados");
}


	$(document).ready(function() {

		//Opciones jquery.forms
		    var options2 = { 
		        beforeSubmit:  showRequest2,  // Funcion a ejecutar antes de enviarse
		        success:       showResponse2,  //Funcion a ejecutar despues de enviarse
		        dataType:  'json' //tipo de dato a devolver
		      }; 


		      $("#crear_btn").click(function() {
			      $('#new_orden').ajaxSubmit(options2); 
		      })
		 	

		    
		    


	
		

	})
</script>