config/routes.rb
  get 'plan-mejoramiento-educativo/get_pme_estrategia' => 'pme_objetivo_estrategia#get_pme_estrategia', as: :get_pme_estrategia
  get 'plan-mejoramiento-educativo/:est/objetivo/:id/estrategia' => 'pme_objetivo_estrategia#estrategia_objetivo', as: :pme_estrategias_objetivo
  post 'plan-mejoramiento-educativo/:est/editar/:id/crear_estrategia' => 'pme_objetivo_estrategia#crear_estrategia', as: :pme_crear_estrategia
  post 'plan-mejoramiento-educativo/:est/eliminar/:id/estrategia' => 'pme_objetivo_estrategia#eliminar_estrategia', as: :pme_eliminar_estrategia
  post 'plan-mejoramiento-educativo/jeditable_nombre_pme_estrategia' => 'pme_objetivo_estrategia#jeditable_nombre_pme_estrategia', as: :jeditable_nombre_pme_estrategia
  post 'plan-mejoramiento-educativo/:id/destroy_pme_estrategia' => 'pme_objetivo_estrategia#destroy_pme_estrategia', as: :destroy_pme_estrategia

  get 'plan-mejoramiento-educativo/get_pme_accion' => 'pme_accion#get_pme_accion', as: :get_pme_accion
  get 'plan-mejoramiento-educativo/sl_pme_accion' => 'pme_accion#sl_pme_accion', as: :sl_pme_accion
  get 'plan-mejoramiento-educativo/:est/acciones' => 'pme_accion#index', as: :pme_acciones
  get 'plan-mejoramiento-educativo/:est/nueva' => 'pme_accion#nueva', as: :pme_nueva_accion
  post 'plan-mejoramiento-educativo/:est/crear' => 'pme_accion#crear', as: :pme_crear_accion
  get 'plan-mejoramiento-educativo/:est/ver/:id/accion' => 'pme_accion#ver', as: :pme_ver_accion
  post 'plan-mejoramiento-educativo/:est/editar/:id/accion' => 'pme_accion#editar', as: :pme_editar_accion
  post 'plan-mejoramiento-educativo/:est/eliminar/:id/accion' => 'pme_accion#eliminar', as: :pme_eliminar_accion

  get 'plan-mejoramiento-educativo/:est/ver/:id/accion/:act/actividad' => 'pme_actividad#ver', as: :pme_ver_actividad
  get 'plan-mejoramiento-educativo/:est/ver/:id/pme_nueva_actividad' => 'pme_actividad#nueva', as: :pme_nueva_actividad
  post 'plan-mejoramiento-educativo/:id/crea_actividad' => 'pme_actividad#crear', as: :pme_crea_actividad
  post 'plan-mejoramiento-educativo/:id/actualiza_actividad' => 'pme_actividad#actualiza', as: :pme_actualiza_actividad
  post 'plan-mejoramiento-educativo/:id/subir_pme_actividad_doc' => 'pme_actividad#subir_pme_actividad_doc', as: :subir_pme_actividad_doc

  get 'opi/nueva' => 'opi#nueva', as: :nueva_opi
  post 'opi/crear' => 'opi#crear', as: :crear_opi
  get 'opi/validar' => 'opi#validar', as: :validar_opi
  get 'opi/:id/ver' => 'opi#ver', as: :ver_opi
  post 'opi/:id/actualizar' => 'opi#actualizar', as: :actualiza_opi

  get 'gestionar/:id/opi' => 'gestionar#opi', as: :gestionar_opi
  post 'gestionar/:id/validar' => 'gestionar#validar', as: :gestionar_validar_opi
  post 'gestionar/:id/sigue_conducto' => 'gestionar#sigue_conducto', as: :sigue_conducto
  post 'gestionar/:id/responde_consulta' => 'gestionar#responde_consulta', as: :responde_consulta
  post 'gestionar/:id/rechazada' => 'gestionar#rechazada', as: :gestionar_rechazada
  post 'gestionar/:id/adquisicion' => 'gestionar#adquisicion', as: :gestionar_adquisicion
  post 'gestionar/:id/termina_decreto' => 'gestionar#termina_decreto', as: :termina_decreto

  get 'xml/' => 'xml#index', as: :xml

  get 'bandejas/' => 'bandeja#index', as: :bandejas
  get 'bandejas/mi-bandeja' => 'bandeja#mi_bandeja', as: :mi_bandeja
  get 'bandejas/asesor_subvencion' => 'bandeja#asesor_subvencion', as: :entrantes_asesor_subvencion
  get 'bandejas/encargado_subvencion' => 'bandeja#encargado_subvencion', as: :entrantes_encargado_subvencion
  get 'bandejas/:id/entrantes' => 'bandeja#entrantes', as: :bandeja_entrantes
  post 'bandejas/guardar' => 'bandeja#guarda', as: :guarda_bandeja
  get 'bandejas/:id/ver' => 'bandeja#ver', as: :ver_bandeja
  post 'bandejas/:id/guarda_usuario' => 'bandeja#guarda_usuario', as: :guarda_usuario_bandeja
  post 'bandejas/:id/elimina_usuario' => 'bandeja#elimina_usuario', as: :elimina_usuario_bandeja

  get 'conducto/' => 'conducto#index', as: :conducto
  post 'conducto/guardar' => 'conducto#guardar', as: :guarda_conducto

  get 'encargados-subvencion/' => 'encargado#encargados', as: :encargados_subvencion
  get 'asesores-subvencion/' => 'encargado#asesores', as: :asesores_subvencion
  post 'encargados-subvencion/guarda_encargado' => 'encargado#guarda_encargado', as: :guarda_encargado
  post 'asesores-subvencion/guarda_asesor' => 'encargado#guarda_asesor', as: :guarda_asesor
  post 'encargados-subvencion/:id/borra_asesor' => 'encargado#borra_asesor', as: :borra_asesor
  post 'asesores-subvencion/:id/borra_encargado' => 'encargado#borra_encargado', as: :borra_encargado

  get 'cuentas_gastos/' => 'cuenta_gastos#index', as: :cuentas_gastos
  post 'cuentas_gastos/guardar' => 'cuenta_gastos#guardar', as: :guarda_cuenta_gasto
  post 'cuentas_gastos/eliminar' => 'cuenta_gastos#eliminar', as: :eliminar_cuenta_gasto

  get 'usuarios/' => 'usuarios#index', as: :usuarios
  get 'usuarios/nuevo' => 'usuarios#nuevo', as: :nuevo_usuario
  get 'usuarios/bajas' => 'usuarios#bajas', as: :bajas_usuario
  post 'usuarios/guardar' => 'usuarios#guardar', as: :guardar_usuario
  get 'usuarios/:id/editar' => 'usuarios#editar', as: :editar_usuario
  get 'usuarios/:id/perfil' => 'usuarios#perfil', as: :perfil
  post 'usuarios/:id/actualizar' => 'usuarios#actualizar', as: :actualizar_usuario
  post 'usuarios/:id/actualizar_perfil' => 'usuarios#actualizar_perfil', as: :actualizar_perfil
  post 'usuarios/:id/actualiza_password' => 'usuarios#actualiza_password', as: :actualiza_password
  post 'usuarios/:id/baja' => 'usuarios#baja', as: :baja
  get 'usuarios/get_usuario' => 'usuarios#get_usuario', as: :get_usuario

    get 'establecimiento/' => 'establecimientos#index', as: :establecimientos
    get 'establecimiento/nuevo' => 'establecimientos#new', as: :nuevo_establecimiento
    post 'establecimiento/guardar' => 'establecimientos#create', as: :guardar_establecimiento
    get 'establecimiento/get_dpto' => 'establecimientos#get_dpto', as: :get_dpto
    get 'establecimiento/get_dpto_usuario' => 'establecimientos#get_dpto_usuario', as: :get_dpto_usuario
    get 'establecimiento/:id/ver' => 'establecimientos#show', as: :ver_establecimiento
    post 'establecimiento/:id/actualizar' => 'establecimientos#update', as: :actualizar_establecimiento
    post 'establecimiento/:id/eliminar' => 'establecimientos#eliminar_establecimiento', as: :eliminar_establecimiento
    

    get 'departamento/:id/ver' => 'establecimientos#departamento', as: :ver_departamento
    post 'departamento/:id/actualizar' => 'establecimientos#actualizar_departamento', as: :actualizar_departamento
    post 'departamento/:id/guardar' => 'establecimientos#guardar_departamento', as: :guardar_departamento
    post 'departamento/:id/eliminar' => 'establecimientos#eliminar_departamento', as: :eliminar_departamento

   

  match(
    "home/general" => "home#general",
    :as => :general,
    :via => :get
  )

  match(
    "home/:id/dashboard" => "home#dashboard",
    :as => :dashboard,
    :via => :get
  )

  match(
    "pagar/index" => "pagar#index",
    :as => :pagar,
    :via => :get
  )
   match(
    "pagar/todas_recepciones" => "pagar#todas_recepciones",
    :as => :todas_recepciones,
    :via => :get
  ) 
   match(
    "pagar/:id/ver" => "pagar#ver",
    :as => :ver_pagar,
    :via => :get
  )  
  match(
    "pagar/:id/quitar_lista_pagar" => "pagar#quitar_lista_pagar",
    :as => :quitar_lista_pagar,
    :via => :post
  )
   match(
    "pagar/:id/guarda_cheque" => "pagar#guarda_cheque",
    :as => :guarda_cheque,
    :via => :post
  ) 
  match(
    "informe/gastos-categoria" => "informe#gastos_categoria",
    :as => :gastos_categoria,
    :via => :get
  )
  match(
    "informe/informe_gastos_categoria" => "informe#informe_gastos_categoria",
    :as => :informe_gastos_categoria,
    :via => :get  )

  match(
    "informe/gastos-subvencion" => "informe#gastos_subvencion",
    :as => :gastos_subvencion,
    :via => :get
  )
   match(
    "informe/informe_gastos_subvencion" => "informe#informe_gastos_subvencion",
    :as => :informe_gastos_subvencion,
    :via => :get  )
  match(
    "informe/:id/gastos-subvencion" => "informe#ver_gastos_subvencion",
    :as => :ver_gastos_subvencion,
    :via => :get,
    :format => "pdf"
  )

  match(
    "informe/ingresos-subvencion" => "informe#ingresos_subvencion",
    :as => :ingresos_subvencion,
    :via => :get
  )
  match(
    "informe/:id/ingresos-subvencion" => "informe#ver_ingresos_subvencion",
    :as => :ver_ingresos_subvencion,
    :via => :get,
    :format => "pdf"
  )

  match(
    "informe/compras" => "informe#compras",
    :as => :informe_compras,
    :via => :get
  )
  match(
    "informe/informe_compras" => "informe#informe_compras",
    :as => :genera_informe_compras,
    :via => :get  )
  match(
    "informe/:id/ver-compras" => "informe#ver_compras",
    :as => :ver_informe_compras,
    :via => :get,
    :format => "pdf"
  )

  match(
    "informe/supereduc" => "informe#supereduc",
    :as => :supereduc,
    :via => :get
  )
  match(
    "informe/informe_supereduc" => "informe#informe_supereduc",
    :as => :informe_supereduc,
    :via => :get  )
  match(
    "informe/:id/generar-supereduc" => "informe#generar_supereduc",
    :as => :generar_supereduc,
    :via => :get
  )
  match(
    "recepcionar" => "recepcionar#index",
    :as => :recepcionar,
    :via => :get
  )

  match(
    "recepcionar/crear" => "recepcionar#crear",
    :as => :crear_recepcion,
    :via => :post
  )
  match(
    "recepcionar/seleccionar" => "recepcionar#seleccionar",
    :as => :seleccionar_recepcion,
    :via => :post
  )
  match(
    "recepcionar/listado" => "recepcionar#listado",
    :as => :listado_recepcionadas,
    :via => :get
  )
  match(
    "recepcionar/para_firma" => "recepcionar#para_firma",
    :as => :para_firmar_recepcion,
    :via => :get
  )
  match(
    "recepcionar/visar_adq" => "recepcionar#visar_adq",
    :as => :visar_adq,
    :via => :get
  )
  match(

app/controllers/encargado_controller.rb
class EncargadoController < ApplicationController

	def asesores
		@funcionarios = Usuario.daem

		@vigentes = AsesorSubvencion.all(:es_vigente => true)
	end

	def guarda_asesor
		asesor = AsesorSubvencion.new params[:sub]

		#puts "#{asesor.inspect}".blue
		asesor.save

		flash[:notificacion] = "Guardado con exito"
		redirect_to :back

	rescue Exception => e
		flash[:error] = "#{e.message}"

		puts "#{e.backtrace}".red
		redirect_to :back
	end

	def borra_asesor
		asesor = AsesorSubvencion.get params[:id]
		asesor.update :es_vigente => false
	
		flash[:notificacion] = "Eliminado con exito"
		redirect_to :back

	rescue Exception => e
		flash[:error] = "#{e.message}"
		puts "#{e.backtrace}".red
		redirect_to :back
	end


	def encargados
		@funcionarios = Usuario.daem

		@vigentes = EncargadoSubvencion.all(:es_vigente => true)
	end

	def guarda_encargado
		encargado = EncargadoSubvencion.new params[:sub]

		#puts "#{encargado.inspect}".blue
		encargado.save

		flash[:notificacion] = "Guardado con exito"
		redirect_to :back

	rescue Exception => e
		flash[:error] = "#{e.message}"

		puts "#{e.backtrace}".red
		redirect_to :back
	end

	def borra_encargado
		encargado = EncargadoSubvencion.get params[:id]
		encargado.update :es_vigente => false
	
		flash[:notificacion] = "Eliminado con exito"
		redirect_to :back

	rescue Exception => e
		flash[:error] = "#{e.message}"
		puts "#{e.backtrace}".red
		redirect_to :back
	end
end

app/helpers/encargado_helper.rb
module EncargadoHelper
end

app/views/encargado/asesores.html.erb
<h1>Asesores Subvencion</h1>
<% Subvencion.todos.each do |s| %>

<div class="row">
  <div class="col-lg-12">
    <div class="main-box clearfix">
      <header class="main-box-header clearfix">
        <h2 class="pull-left"><%= s.nombre %></h2>
      </header>
      <div class="main-box-body clearfix">
        
        
          <div class="form-horizontal form-label-left">
          <form method="post" action="<%= guarda_asesor_path %>">
            <div class="form-group">
              <label for="cod" class="control-label col-sm-2">Funcionario: </label>
              <div class="col-sm-6">
                <select class="form-control" name="sub[usuario_id]">
                		<option>Seleccione Nuevo Asesor <%= s.nombre %></option>
                	<% @funcionarios.each do |u| %>
                		<option value="<%= u.id %>"><%= u.apaterno.upcase %> <%= u.amaterno.upcase %> <%= u.nombre.upcase %></option>
                	<% end %>
                </select>
                <input type="hidden" name="sub[subvencion_id]" value="<%= s.id %>">
              </div>
              <div class="col-sm-4">
                <button type="submit" class="btn btn-sm btn-success"><i class="fa fa-plus"></i> Agregar</button>
              </div>
            </div>
            </form>
            <div class="form-group">
              <label for="cod" class="control-label col-sm-2">Vigentes: </label>
              <div class="col-sm-10">
                <table class="table" style="font-size: 11px;" >
                	<thead>
                		<th>Funcionario</th>
                		<th>Desde</th>
                		<th></th>
                	</thead>
                	<tbody>
                		<% @vigentes.all(:subvencion_id => s.id).each do |v| %>
                		<tr>
                			<td><%= v.usuario.apaterno.upcase %> <%= v.usuario.amaterno.upcase %> <%= v.usuario.nombre.upcase %></td>
                			<td><%= fecha(v.created_at) %></td>
                			<td>
                				<form method="post" action="<%= borra_asesor_path v.id %>">
                				<button type="submit" class="btn btn-default btn-sm"><i class="fa fa-remove"></i> Quitar</button>
                				</form>
                			</td>
                		</tr>
                		<% end %>
                	</tbody>
                </table>
              </div>

            </div>

            

          </div>
        
      </div>
    </div>
  </div>
</div>
<% end %>




	



app/views/encargado/encargados.html.erb
<h1>Encargados Subvencion</h1>
<% Subvencion.todos.each do |s| %>

<div class="row">
  <div class="col-lg-12">
    <div class="main-box clearfix">
      <header class="main-box-header clearfix">
        <h2 class="pull-left"><%= s.nombre %></h2>
      </header>
      <div class="main-box-body clearfix">
        
        
          <div class="form-horizontal form-label-left">
          <form method="post" action="<%= guarda_encargado_path %>">
            <div class="form-group">
              <label for="cod" class="control-label col-sm-2">Funcionario: </label>
              <div class="col-sm-6">
                <select class="form-control" name="sub[usuario_id]">
                		<option>Seleccione Nuevo Encargado <%= s.nombre %></option>
                	<% @funcionarios.each do |u| %>
                		<option value="<%= u.id %>"><%= u.apaterno.upcase %> <%= u.amaterno.upcase %> <%= u.nombre.upcase %></option>
                	<% end %>
                </select>
                <input type="hidden" name="sub[subvencion_id]" value="<%= s.id %>">
              </div>
              <div class="col-sm-4">
                <button type="submit" class="btn btn-sm btn-success"><i class="fa fa-plus"></i> Agregar</button>
              </div>
            </div>
            </form>
            <div class="form-group">
              <label for="cod" class="control-label col-sm-2">Vigentes: </label>
              <div class="col-sm-10">
                <table class="table" style="font-size: 11px;" >
                	<thead>
                		<th>Funcionario</th>
                		<th>Desde</th>
                		<th></th>
                	</thead>
                	<tbody>
                		<% @vigentes.all(:subvencion_id => s.id).each do |v| %>
                		<tr>
                			<td><%= v.usuario.apaterno.upcase %> <%= v.usuario.amaterno.upcase %> <%= v.usuario.nombre.upcase %></td>
                			<td><%= fecha(v.created_at) %></td>
                			<td>
                				<form method="post" action="<%= borra_encargado_path v.id %>">
                				<button type="submit" class="btn btn-default btn-sm"><i class="fa fa-remove"></i> Quitar</button>
                				</form>
                			</td>
                		</tr>
                		<% end %>
                	</tbody>
                </table>
              </div>

            </div>

            

          </div>
        
      </div>
    </div>
  </div>
</div>
<% end %>




	

