config/routes.rb
Educa::Application.routes.draw do

  root :to => "home#redirigir"

  get 'home/redirigir' => 'home#redirigir', as: :redirigir

  get 'suministros/' => 'suministro#index', as: :suministros
  get 'suministros/nuevo' => 'suministro#nuevo', as: :nuevo_suministro
  post 'suministros/guardar' => 'suministro#guardar', as: :guardar_suministro
  get 'suministros/:id/ver' => 'suministro#ver', as: :ver_suministro
  post 'suministros/:id/actualizar' => 'suministro#actualizar', as: :actualizar_suministro
  post 'suministros/:id/eliminar' => 'suministro#eliminar', as: :eliminar_suministro
  get 'suministros/:id/ver_orden' => 'suministro#ver_orden', as: :ver_orden_suministro
  post 'suministros/:id/asignar_orden' => 'suministro#asignar_orden', as: :asignar_orden
  post 'suministros/:id/quitar_orden' => 'suministro#quitar_orden', as: :quitar_orden

  get 'dotacion-docente/solicitudes' => 'dotacion_docente#solicitudes', as: :solicitudes_dotacion
  get 'dotacion-docente/solicitudes-enviadas' => 'dotacion_docente#solicitudes_enviadas', as: :solicitudes_enviadas
  get 'dotacion-docente/nueva-solicitud' => 'dotacion_docente#nueva', as: :nueva_solicitud_dotacion
  post 'dotacion-docente/crear-solicitud' => 'dotacion_docente#crea_solicitud', as: :crea_solicitud_dotacion
  get 'dotacion-docente/reemplazos-activos' => 'dotacion_docente#remplazos_activos', as: :remplazos_activos
  get 'dotacion-docente/reemplazos-terminados' => 'dotacion_docente#remplazos_terminados', as: :remplazos_terminados
  get 'dotacion-docente/:id/ver-solicitud' => 'dotacion_docente#ver_solicitud', as: :ver_solicitud_dotacion
  post 'dotacion-docente/:id/guarda-doc' => 'dotacion_docente#guarda_doc_solicitud', as: :guarda_doc_solicitud
  post 'dotacion-docente/:id/elimina-doc' => 'dotacion_docente#elimina_doc_solicitud', as: :elimina_doc_solicitud
  post 'dotacion-docente/:id/actualizar-solicitud' => 'dotacion_docente#actualizar_solicitud', as: :actualizar_solicitud_dotacion
 

  post 'firma_usuario/:id/sube' => 'firma_usuario#sube', as: :sube_firma
  post 'firma_usuario/:id/borra' => 'firma_usuario#borra', as: :borra_firma

  post 'dotacion-docente/actualizar-docente' => 'docente#actualizar_docente', as: :actualizar_docente
  get 'dotacion-docente/get-docente' => 'docente#get_docente', as: :get_docente
  get 'dotacion-docente/:id/ver-docente' => 'docente#ver_docente', as: :ver_docente

  get 'plan-mejoramiento-educativo/dimensiones' => 'pme_parametros#dimensiones', as: :pme_dimensiones
  post 'plan-mejoramiento-educativo/create_pme_dimension' => 'pme_parametros#create_pme_dimension', as: :create_pme_dimension
  post 'plan-mejoramiento-educativo/:id/destroy_pme_dimension' => 'pme_parametros#destroy_pme_dimension', as: :destroy_pme_dimension
  post 'plan-mejoramiento-educativo/jeditable_nombre_pme_dimension' => 'pme_parametros#jeditable_nombre_pme_dimension', as: :jeditable_nombre_pme_dimension
  get 'plan-mejoramiento-educativo/get_pme_dimension' => 'pme_parametros#get_pme_dimension', as: :get_pme_dimension

  get 'plan-mejoramiento-educativo/:id/subdimensiones' => 'pme_parametros#subdimensiones', as: :pme_subdimensiones
  post 'plan-mejoramiento-educativo/create_pme_subdimension' => 'pme_parametros#create_pme_subdimension', as: :create_pme_subdimension
  post 'plan-mejoramiento-educativo/:id/destroy_pme_subdimension' => 'pme_parametros#destroy_pme_subdimensiones', as: :destroy_pme_subdimensiones
  post 'plan-mejoramiento-educativo/jeditable_nombre_pme_subdimensiones' => 'pme_parametros#jeditable_nombre_pme_subdimensiones', as: :jeditable_nombre_pme_subdimensiones
  get 'plan-mejoramiento-educativo/get_pme_subdimension' => 'pme_parametros#get_pme_subdimension', as: :get_pme_subdimension

  get 'plan-mejoramiento-educativo/get_pme_objetivo' => 'pme_objetivo_estrategia#get_pme_objetivo', as: :get_pme_objetivo
  get 'plan-mejoramiento-educativo/:est/objetivos' => 'pme_objetivo_estrategia#objetivos', as: :pme_objetivos
  get 'plan-mejoramiento-educativo/:est/nuevo_objetivo' => 'pme_objetivo_estrategia#nuevo_objetivo', as: :pme_nuevo_objetivo
  post 'plan-mejoramiento-educativo/:est/crear_objetivo' => 'pme_objetivo_estrategia#crear_objetivo', as: :pme_crear_objetivo
  post 'plan-mejoramiento-educativo/jeditable_nombre_pme_objetivo' => 'pme_objetivo_estrategia#jeditable_nombre_pme_objetivo', as: :jeditable_nombre_pme_objetivo
  post 'plan-mejoramiento-educativo/:id/destroy_pme_objetivo' => 'pme_objetivo_estrategia#destroy_pme_objetivo', as: :destroy_pme_objetivo
 
  get 'plan-mejoramiento-educativo/get_pme_estrategia' => 'pme_objetivo_estrategia#get_pme_estrategia', as: :get_pme_estrategia
  get 'plan-mejoramiento-educativo/:est/objetivo/:id/estrategia' => 'pme_objetivo_estrategia#estrategia_objetivo', as: :pme_estrategias_objetivo
  post 'plan-mejoramiento-educativo/:est/editar/:id/crear_estrategia' => 'pme_objetivo_estrategia#crear_estrategia', as: :pme_crear_estrategia
  post 'plan-mejoramiento-educativo/:est/eliminar/:id/estrategia' => 'pme_objetivo_estrategia#eliminar_estrategia', as: :pme_eliminar_estrategia
  post 'plan-mejoramiento-educativo/jeditable_nombre_pme_estrategia' => 'pme_objetivo_estrategia#jeditable_nombre_pme_estrategia', as: :jeditable_nombre_pme_estrategia
  post 'plan-mejoramiento-educativo/:id/destroy_pme_estrategia' => 'pme_objetivo_estrategia#destroy_pme_estrategia', as: :destroy_pme_estrategia

  get 'plan-mejoramiento-educativo/get_pme_accion' => 'pme_accion#get_pme_accion', as: :get_pme_accion
  get 'plan-mejoramiento-educativo/sl_pme_accion' => 'pme_accion#sl_pme_accion', as: :sl_pme_accion
  get 'plan-mejoramiento-educativo/:est/acciones' => 'pme_accion#index', as: :pme_acciones
  get 'plan-mejoramiento-educativo/:est/nueva' => 'pme_accion#nueva', as: :pme_nueva_accion
  post 'plan-mejoramiento-educativo/:est/crear' => 'pme_accion#crear', as: :pme_crear_accion
  get 'plan-mejoramiento-educativo/:est/ver/:id/accion' => 'pme_accion#ver', as: :pme_ver_accion
  post 'plan-mejoramiento-educativo/:est/editar/:id/accion' => 'pme_accion#editar', as: :pme_editar_accion
  post 'plan-mejoramiento-educativo/:est/eliminar/:id/accion' => 'pme_accion#eliminar', as: :pme_eliminar_accion

  get 'plan-mejoramiento-educativo/:est/ver/:id/accion/:act/actividad' => 'pme_actividad#ver', as: :pme_ver_actividad
  get 'plan-mejoramiento-educativo/:est/ver/:id/pme_nueva_actividad' => 'pme_actividad#nueva', as: :pme_nueva_actividad
  post 'plan-mejoramiento-educativo/:id/crea_actividad' => 'pme_actividad#crear', as: :pme_crea_actividad
  post 'plan-mejoramiento-educativo/:id/actualiza_actividad' => 'pme_actividad#actualiza', as: :pme_actualiza_actividad
  post 'plan-mejoramiento-educativo/:id/subir_pme_actividad_doc' => 'pme_actividad#subir_pme_actividad_doc', as: :subir_pme_actividad_doc

  get 'opi/nueva' => 'opi#nueva', as: :nueva_opi
  post 'opi/crear' => 'opi#crear', as: :crear_opi
  get 'opi/validar' => 'opi#validar', as: :validar_opi
  get 'opi/:id/ver' => 'opi#ver', as: :ver_opi
  post 'opi/:id/actualizar' => 'opi#actualizar', as: :actualiza_opi

  get 'gestionar/:id/opi' => 'gestionar#opi', as: :gestionar_opi
  post 'gestionar/:id/validar' => 'gestionar#validar', as: :gestionar_validar_opi
  post 'gestionar/:id/sigue_conducto' => 'gestionar#sigue_conducto', as: :sigue_conducto
  post 'gestionar/:id/responde_consulta' => 'gestionar#responde_consulta', as: :responde_consulta
  post 'gestionar/:id/rechazada' => 'gestionar#rechazada', as: :gestionar_rechazada
  post 'gestionar/:id/adquisicion' => 'gestionar#adquisicion', as: :gestionar_adquisicion
  post 'gestionar/:id/termina_decreto' => 'gestionar#termina_decreto', as: :termina_decreto

  get 'xml/' => 'xml#index', as: :xml

  get 'bandejas/' => 'bandeja#index', as: :bandejas
  get 'bandejas/mi-bandeja' => 'bandeja#mi_bandeja', as: :mi_bandeja
  get 'bandejas/asesor_subvencion' => 'bandeja#asesor_subvencion', as: :entrantes_asesor_subvencion
  get 'bandejas/encargado_subvencion' => 'bandeja#encargado_subvencion', as: :entrantes_encargado_subvencion
  get 'bandejas/:id/entrantes' => 'bandeja#entrantes', as: :bandeja_entrantes
  post 'bandejas/guardar' => 'bandeja#guarda', as: :guarda_bandeja
  get 'bandejas/:id/ver' => 'bandeja#ver', as: :ver_bandeja
  post 'bandejas/:id/guarda_usuario' => 'bandeja#guarda_usuario', as: :guarda_usuario_bandeja
  post 'bandejas/:id/elimina_usuario' => 'bandeja#elimina_usuario', as: :elimina_usuario_bandeja

  get 'conducto/' => 'conducto#index', as: :conducto
  post 'conducto/guardar' => 'conducto#guardar', as: :guarda_conducto

  get 'encargados-subvencion/' => 'encargado#encargados', as: :encargados_subvencion
  get 'asesores-subvencion/' => 'encargado#asesores', as: :asesores_subvencion
  post 'encargados-subvencion/guarda_encargado' => 'encargado#guarda_encargado', as: :guarda_encargado
  post 'asesores-subvencion/guarda_asesor' => 'encargado#guarda_asesor', as: :guarda_asesor
  post 'encargados-subvencion/:id/borra_asesor' => 'encargado#borra_asesor', as: :borra_asesor
  post 'asesores-subvencion/:id/borra_encargado' => 'encargado#borra_encargado', as: :borra_encargado

  get 'cuentas_gastos/' => 'cuenta_gastos#index', as: :cuentas_gastos
  post 'cuentas_gastos/guardar' => 'cuenta_gastos#guardar', as: :guarda_cuenta_gasto
  post 'cuentas_gastos/eliminar' => 'cuenta_gastos#eliminar', as: :eliminar_cuenta_gasto

  get 'usuarios/' => 'usuarios#index', as: :usuarios
  get 'usuarios/nuevo' => 'usuarios#nuevo', as: :nuevo_usuario
  get 'usuarios/bajas' => 'usuarios#bajas', as: :bajas_usuario
  post 'usuarios/guardar' => 'usuarios#guardar', as: :guardar_usuario
  get 'usuarios/:id/editar' => 'usuarios#editar', as: :editar_usuario
  get 'usuarios/:id/perfil' => 'usuarios#perfil', as: :perfil
  post 'usuarios/:id/actualizar' => 'usuarios#actualizar', as: :actualizar_usuario
  post 'usuarios/:id/actualizar_perfil' => 'usuarios#actualizar_perfil', as: :actualizar_perfil
  post 'usuarios/:id/actualiza_password' => 'usuarios#actualiza_password', as: :actualiza_password

app/controllers/home_controller.rb
#encoding: utf-8
class HomeController < ApplicationController




	def general
		periodo = session[:periodo].id
		est = @usuario_actual.departamento.establecimiento_id
		respond_to do |format|
	      format.html 
	      format.json { render json: OpisDatatable.new(view_context, periodo, est) }
	    end
		
	end

	def redirigir
		if @usuario_actual.encargado_subvencions(:es_vigente => true).count > 0

			redirect_to entrantes_encargado_subvencion_path

		elsif  @usuario_actual.asesor_subvencions(:es_vigente => true).count > 0

			redirect_to entrantes_asesor_subvencion_path

		elsif not @usuario_actual.bandeja_usuarios.blank?

			 redirect_to bandeja_entrantes_path @usuario_actual.bandeja_usuarios.first.bandeja_id
		else
			redirect_to mi_bandeja_path
		end
	end


	def dashboard
		@e = Establecimiento.get params[:id]
		@ordenes_totales = Orden.count(:periodo_id => session[:periodo].id.to_i, :es_nula => false);
		@ordenes_proceso = Orden.count(:periodo_id => session[:periodo].id.to_i, :es_nula => false);
			
		@o = Orden.all(
			:periodo_id => session[:periodo].id.to_i, 
			:es_nula => false, 
			:departamento => {
				:establecimiento_id => @e.id
				},
			:es_entrante => true
			)

		@dpto_direccion = Departamento.first(:es_direccion => true, :establecimiento_id => @e.id)
		@ordenes_director = @o.count(:estado => "En digitacion", :ubicacion => {:departamento_id => @dpto_direccion.id})
		@ordenes_daem =  @o.count(:estado => "En proceso", :ubicacion => {:departamento_id => 10})
		@ordenes_consulta = @o.count(:estado => "En consulta") 
		@ordenes_finanzas = @o.count(:estado => "En proceso", :ubicacion => {:departamento_id => 2})
		@ordenes_adquisiciones = @o.count(:ubicacion => {:departamento_id => 1}) 

Subvencion.todos.each do |s|
	 			 	end

	 @o.map do |sub|
	 	{
	 		 
	 	}
	 end

		


	end

	def perfil
		
	end

	def actualiza_perfil
		user = Usuario.get @usuario_actual.id
		user.update params[:usuario]
		redirect_to perfil_path
		flash[:notificacion] = "Se ha actualizado su perfil exitosamente"
	rescue
		flash[:error] = "Error, verifique los campos ingresados e intentelo nuevamente"
		redirect_to perfil_path
	end

	def pass
		
	end

	def actualiza_pass

		if params[:nueva] == params[:verifica]
			if params[:actual] == @usuario_actual.password
				user = Usuario.get @usuario_actual.id
				user.update(:password => params[:nueva])
				flash[:notificacion] = "Se ha cambiado su password exitosamente"

			else
				flash[:error] = "Password actual es erronea, intentelo nuevamente"
			end
		else
			flash[:error] = "Las passwords no coinciden, intentelo nuevamente"
		end
		redirect_to pass_path
		rescue
			flash[:error] = "ha ocurrido un error cambiando su password, intentelo nuevamente"
			redirect_to pass_path
	end
end

app/views/home/dashboard.html.erb
<div class="row">
	<div class="col-lg-12">
		<ol class="breadcrumb">
			<li><a href="#">Gestión de Subvenciones</a></li>
			<li class="active"><span>Inicio</span></li>
		</ol>
		<h1>Dashboard</h1>
	</div>
	  		<div class="form-group" >
									<select class="form-control" id="sel_establecimiento" <% if @usuario_actual.departamento.establecimiento_id != 1 %> disabled <% end %> onchange="location = this.value;">
								<% Establecimiento.todos.each do |e| %>
									<option value="<%= dashboard_path e.id %>" <% if @e.id == e.id %> selected <% end %> ><%= e.nombre %></option>
								<% end %>
								</select>
									</div>
</div>
<div class="row">
	<div class="col-lg-6">
		<div class="main-box clearfix">
			<header class="main-box-header clearfix">
				<h2 class="pull-left">Ubicaciones Ordenes</h2>

			</header>
			<div class="main-box-body clearfix">

				<div id="hero-bar" style="height: 250px;"></div>
			</div>
		</div>
	</div>
	<%= content_tag :div, "", id: "ordenes" %>
	<div class="col-lg-6">
		<div class="main-box clearfix">
			<header class="main-box-header clearfix">
				<h2 class="pull-left">Subvenciones totales ordenes</h2>

			</header>
			<div class="main-box-body clearfix">

				<div id="hero-donut" style="height: 250px;"></div>
			</div>
		</div>
	</div>
</div>
<div class="row">


	<div class="col-md-4 col-sm-6 col-xs-12">
		<div class="main-box small-graph-box emerald-bg">
			<span class="value"><%= @ordenes_totales %></span>
			<span class="headline">Ordenes Totales</span>
			<div class="progress">
				<div style="width: 84%;" aria-valuemax="100" aria-valuemin="0" aria-valuenow="84" role="progressbar" class="progress-bar">
					<span class="sr-only">84% Complete</span>
				</div>
			</div>
			<span class="subinfo">
				<i class="fa fa-arrow-circle-o-down"></i> 9 Creadas este mes
			</span>
			<span class="subinfo">
				<i class="fa fa-globe"></i> 0 Creadas Hoy
			</span>	
		</div>
	</div>
	<div class="col-md-4 col-sm-6 col-xs-12">
	<div class="main-box small-graph-box " style="background:#EA9E14!important;">
			<span class="value"><%= @ordenes_proceso %></span>
			<span class="headline">En Proceso</span>
			<div class="progress">
				<div style="width: 100%;" aria-valuemax="100" aria-valuemin="0" aria-valuenow="60" role="progressbar" class="progress-bar">
					<span class="sr-only">100% Complete</span>
				</div>
			</div>
			<span class="subinfo">
				<i class="fa fa-arrow-circle-o-up"></i> 100% de el total
			</span>
			<span class="subinfo">
				<i class="fa fa-users"></i> 0 en Licitación
			</span>
		</div>
	</div>
	<div class="col-md-4 col-sm-6 col-xs-12 hidden-sm">
		<div class="main-box small-graph-box green-bg">
			<span class="value">0</span>
			<span class="headline">Completadas </span>
			<div class="progress">
				<div style="width: 0%;" aria-valuemax="100" aria-valuemin="0" aria-valuenow="42" role="progressbar" class="progress-bar">
					<span class="sr-only">0% Complete</span>
				</div>
			</div>
			<span class="subinfo">
				<i class="fa fa-arrow-circle-o-up"></i> 0% de el total 
			</span>
			<span class="subinfo">
				<i class="fa fa-remove"></i> 0 Rechazadas
			</span>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-lg-12">
		<div class="main-box clearfix">
			<header class="main-box-header clearfix">
				<h2 class="pull-left">Ingresos Gastos</h2>

			</header>
			<div class="main-box-body clearfix">
		
				<div id="hero-graph" style="height: 250px;"></div>
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-lg-12">
		<div class="main-box clearfix">
			<header class="main-box-header clearfix">
				<h2 class="pull-left">Gasto Subvenciones</h2>

			</header>
			<div class="main-box-body clearfix">
				<div class="form-group" >
									<select class="form-control">
									<%= Subvencion.todos.each do |e| %>
										<option value="<%= e.id %>"><%= e.nombre %></option>
									<% end %>
									</select>
									</div>
				<div id="hero-area" style="height: 250px;"></div>
			</div>
		</div>
	</div>
</div>




<div class="row">
	
</div>

<script type="text/javascript">
	$(document).ready(function() {

		
  Morris.Bar({
    element: 'hero-bar',
    data: [
      {device: 'Director', geekbench: <%= @ordenes_director %>},
      {device: 'Director DAEM', geekbench: <%= @ordenes_daem %>},
      {device: 'En consulta', geekbench: <%= @ordenes_consulta %>},
      {device: 'Finanzas', geekbench: <%= @ordenes_finanzas %>},
      {device: 'Adquisiciones', geekbench: <%= @ordenes_adquisiciones %>},
    ],
    xkey: 'device',
    ykeys: ['geekbench'],
    labels: ['Total'],
    barRatio: 0.4,
    xLabelAngle: 35,
    hideHover: 'auto'
  });

  Morris.Donut({
    element: 'hero-donut',
    data: $("#dona_subv").data("ordenes"),
    formatter: function (y) { return y + "%" }
  });

  // data stolen from http://howmanyleft.co.uk/vehicle/jaguar_'e'_type
  var tax_data = [
       {"period": "2015-03", "Ingreso": 13000000, "Gasto": 09000000},
       {"period": "2015-04", "Ingreso": 15000000, "Gasto": 16000000},
       {"period": "2015-05", "Ingreso": 21000000, "Gasto": 20000000},
       {"period": "2015-06", "Ingreso": 13000000, "Gasto": 10000000},

  ];
		  Morris.Line({
		    element: 'hero-graph',
		    data: tax_data,
		    xkey: 'period',
		    ykeys: ['Ingreso', 'Gasto'],
		    labels: ['Ingreso', 'Gasto']
		  });




  Morris.Area({
    element: 'hero-area',
    data: [
      {period: '2015-03', Presupuesto: 250000, Proceso: 50000, Gastado: 0},
      {period: '2015-04', Presupuesto: 280000, Proceso: 100000, Gastado: 25000},
      {period: '2015-05', Presupuesto: 300000, Proceso: 150000, Gastado: 60000},
      {period: '2015-06', Presupuesto: 150000, Proceso: 130000, Gastado: 200000},
    ],
    xkey: 'period',
    ykeys: ['Presupuesto', 'Proceso', 'Gastado'],
    labels: ['Presupuesto', 'En Proceso', 'Gastado'],
    pointSize: 2,
    hideHover: 'auto'
  });



	})
</script>

app/views/home/general.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="main-box clearfix" style="overflow: scroll;">
      <header class="main-box-header clearfix">
        <h2 class="pull-left">Todas las ordenes, Periodo: <%= session[:periodo].anio %></h2>
        <div class="filter-block pull-right">
          <div class="form-group pull-left">
           
          </div>

        </div>
      </header>
      <div class="main-box-body clearfix">
        
        
<table class="table table-striped" id="datatable" data-source="<%= general_url(format: "json") %>">
            <thead>
              <tr>
                <th>ID</th>
                <th>Recep.</th>
                <th class="text-center">Titulo</th>
                <th class="text-center">Origen</th>
                <th class="text-center">Subvención</th>
                <th class="text-center">estado</th>
                <th class="text-center">Creada</th>
                <th class="text-center">Ubicación</th>
                <th>&nbsp;</th>
              </tr>
            </thead>
            <tbody>
              
            
            </tbody>
          </table>


      </div>
    </div>
  </div>
</div>


<script type="text/javascript">
$(document).ready(function() {
   $('#datatable').dataTable({
          "sDom": "R<'row-fluid'<'span6'l><'span6'f>r>t<'row-fluid'<'span6'i><'span6'p>>",
          "sPaginationType": "full_numbers",
          "aaSorting": [[0,'desc']],
          "bProcessing": true,
          "bServerSide": true,
          "sAjaxSource": $('#datatable').data('source')
      });



  $('[data-toggle="tooltip"]').tooltip()

})
</script>

app/views/home/pass.html.erb
<form action="<%= actualiza_pass_path %>" method="post">
<div class="row form-horizontal">
	<div class="col-lg-12">
		<div class="main-box">
			<header class="main-box-header clearfix">
				<h2>Cambia Password </h2>
			</header>
			<div class="main-box-body clearfix">

					<div class="form-group">
						<label class="col-lg-2 control-label">Actual</label>
						<div class="col-lg-10">
							<input type="password" name="actual" class="form-control required">
						</div>
					</div>
					<div class="form-group">
						<label class="col-lg-2 control-label">Nueva</label>
						<div class="col-lg-10">
							<input type="password" name="nueva" class="form-control required" id="nueva">
						</div>
					</div>
					<div class="form-group">
						<label class="col-lg-2 control-label">Verifica</label>
						<div class="col-lg-10">
							<input type="password" name="verifica" class="form-control required" id="verifica">
						</div>
					</div>
					
					<div class="form-group">
						<label class="col-lg-2 control-label"></label>
						<div class="col-lg-10">
							<button type="submit" class="btn btn-primary">Guardar</button>
						</div>
					</div>
			
			</div>
		</div>
	</div>
</div>
</form>

app/views/home/perfil.html.erb
<form action="<%= actualiza_perfil_path %>" method="post">
<div class="row form-horizontal">
	<div class="col-lg-12">
		<div class="main-box">
			<header class="main-box-header clearfix">
				<h2>Perfil de usuario </h2>
			</header>
			<div class="main-box-body clearfix">

					<div class="form-group">
						<label class="col-lg-2 control-label">Email</label>
						<div class="col-lg-10">
							<input type="email" value="<%= @usuario_actual.email %>" name="usuario[email]" class="form-control required">
						</div>
					</div>
					<div class="form-group">
						<label class="col-lg-2 control-label">Rut</label>
						<div class="col-lg-10">
							<input type="text" value="<%= @usuario_actual.rut %>" name="usuario[rut]" class="form-control required">
						</div>
					</div>
					<div class="form-group">
						<label class="col-lg-2 control-label">Nombres</label>
						<div class="col-lg-10">
							<input type="text" value="<%= @usuario_actual.nombre %>" name="usuario[nombre]" class="form-control required">
						</div>
					</div>
					<div class="form-group">
						<label class="col-lg-2 control-label">A. Paterno</label>
						<div class="col-lg-10">
							<input type="text" value="<%= @usuario_actual.apaterno %>" name="usuario[apaterno]" class="form-control required">
						</div>
					</div>
					<div class="form-group">
						<label class="col-lg-2 control-label">A. Materno</label>
						<div class="col-lg-10">
							<input type="text" value="<%= @usuario_actual.amaterno %>" name="usuario[amaterno]" class="form-control required">
						</div>
					</div>
					<div class="form-group">
						<label class="col-lg-2 control-label"></label>
						<div class="col-lg-10">
							<button type="submit" class="btn btn-primary">Guardar</button>
						</div>
					</div>
			
			</div>
		</div>
	</div>
</div>
</form>