config/routes.rb
Educa::Application.routes.draw do

  root :to => "home#redirigir"

  get 'home/redirigir' => 'home#redirigir', as: :redirigir

  get 'suministros/' => 'suministro#index', as: :suministros
  get 'suministros/nuevo' => 'suministro#nuevo', as: :nuevo_suministro
  post 'suministros/guardar' => 'suministro#guardar', as: :guardar_suministro
  get 'suministros/:id/ver' => 'suministro#ver', as: :ver_suministro
  post 'suministros/:id/actualizar' => 'suministro#actualizar', as: :actualizar_suministro
  post 'suministros/:id/eliminar' => 'suministro#eliminar', as: :eliminar_suministro
  get 'suministros/:id/ver_orden' => 'suministro#ver_orden', as: :ver_orden_suministro
  post 'suministros/:id/asignar_orden' => 'suministro#asignar_orden', as: :asignar_orden
  post 'suministros/:id/quitar_orden' => 'suministro#quitar_orden', as: :quitar_orden

  get 'dotacion-docente/solicitudes' => 'dotacion_docente#solicitudes', as: :solicitudes_dotacion
  get 'dotacion-docente/solicitudes-enviadas' => 'dotacion_docente#solicitudes_enviadas', as: :solicitudes_enviadas
  get 'dotacion-docente/nueva-solicitud' => 'dotacion_docente#nueva', as: :nueva_solicitud_dotacion
  post 'dotacion-docente/crear-solicitud' => 'dotacion_docente#crea_solicitud', as: :crea_solicitud_dotacion
  get 'dotacion-docente/reemplazos-activos' => 'dotacion_docente#remplazos_activos', as: :remplazos_activos
  get 'dotacion-docente/reemplazos-terminados' => 'dotacion_docente#remplazos_terminados', as: :remplazos_terminados
  get 'dotacion-docente/:id/ver-solicitud' => 'dotacion_docente#ver_solicitud', as: :ver_solicitud_dotacion
  post 'dotacion-docente/:id/guarda-doc' => 'dotacion_docente#guarda_doc_solicitud', as: :guarda_doc_solicitud
  post 'dotacion-docente/:id/elimina-doc' => 'dotacion_docente#elimina_doc_solicitud', as: :elimina_doc_solicitud
  post 'dotacion-docente/:id/actualizar-solicitud' => 'dotacion_docente#actualizar_solicitud', as: :actualizar_solicitud_dotacion
 

  post 'firma_usuario/:id/sube' => 'firma_usuario#sube', as: :sube_firma
  post 'firma_usuario/:id/borra' => 'firma_usuario#borra', as: :borra_firma

  post 'dotacion-docente/actualizar-docente' => 'docente#actualizar_docente', as: :actualizar_docente
  get 'dotacion-docente/get-docente' => 'docente#get_docente', as: :get_docente
  get 'dotacion-docente/:id/ver-docente' => 'docente#ver_docente', as: :ver_docente

  get 'plan-mejoramiento-educativo/dimensiones' => 'pme_parametros#dimensiones', as: :pme_dimensiones
  post 'plan-mejoramiento-educativo/create_pme_dimension' => 'pme_parametros#create_pme_dimension', as: :create_pme_dimension
  post 'plan-mejoramiento-educativo/:id/destroy_pme_dimension' => 'pme_parametros#destroy_pme_dimension', as: :destroy_pme_dimension
  post 'plan-mejoramiento-educativo/jeditable_nombre_pme_dimension' => 'pme_parametros#jeditable_nombre_pme_dimension', as: :jeditable_nombre_pme_dimension
  get 'plan-mejoramiento-educativo/get_pme_dimension' => 'pme_parametros#get_pme_dimension', as: :get_pme_dimension

  get 'plan-mejoramiento-educativo/:id/subdimensiones' => 'pme_parametros#subdimensiones', as: :pme_subdimensiones
  post 'plan-mejoramiento-educativo/create_pme_subdimension' => 'pme_parametros#create_pme_subdimension', as: :create_pme_subdimension
  post 'plan-mejoramiento-educativo/:id/destroy_pme_subdimension' => 'pme_parametros#destroy_pme_subdimensiones', as: :destroy_pme_subdimensiones
  post 'plan-mejoramiento-educativo/jeditable_nombre_pme_subdimensiones' => 'pme_parametros#jeditable_nombre_pme_subdimensiones', as: :jeditable_nombre_pme_subdimensiones
  get 'plan-mejoramiento-educativo/get_pme_subdimension' => 'pme_parametros#get_pme_subdimension', as: :get_pme_subdimension

  get 'plan-mejoramiento-educativo/get_pme_objetivo' => 'pme_objetivo_estrategia#get_pme_objetivo', as: :get_pme_objetivo
  get 'plan-mejoramiento-educativo/:est/objetivos' => 'pme_objetivo_estrategia#objetivos', as: :pme_objetivos
  get 'plan-mejoramiento-educativo/:est/nuevo_objetivo' => 'pme_objetivo_estrategia#nuevo_objetivo', as: :pme_nuevo_objetivo
  post 'plan-mejoramiento-educativo/:est/crear_objetivo' => 'pme_objetivo_estrategia#crear_objetivo', as: :pme_crear_objetivo
  post 'plan-mejoramiento-educativo/jeditable_nombre_pme_objetivo' => 'pme_objetivo_estrategia#jeditable_nombre_pme_objetivo', as: :jeditable_nombre_pme_objetivo
  post 'plan-mejoramiento-educativo/:id/destroy_pme_objetivo' => 'pme_objetivo_estrategia#destroy_pme_objetivo', as: :destroy_pme_objetivo
 
  get 'plan-mejoramiento-educativo/get_pme_estrategia' => 'pme_objetivo_estrategia#get_pme_estrategia', as: :get_pme_estrategia
  get 'plan-mejoramiento-educativo/:est/objetivo/:id/estrategia' => 'pme_objetivo_estrategia#estrategia_objetivo', as: :pme_estrategias_objetivo
  post 'plan-mejoramiento-educativo/:est/editar/:id/crear_estrategia' => 'pme_objetivo_estrategia#crear_estrategia', as: :pme_crear_estrategia
  post 'plan-mejoramiento-educativo/:est/eliminar/:id/estrategia' => 'pme_objetivo_estrategia#eliminar_estrategia', as: :pme_eliminar_estrategia
  post 'plan-mejoramiento-educativo/jeditable_nombre_pme_estrategia' => 'pme_objetivo_estrategia#jeditable_nombre_pme_estrategia', as: :jeditable_nombre_pme_estrategia
  post 'plan-mejoramiento-educativo/:id/destroy_pme_estrategia' => 'pme_objetivo_estrategia#destroy_pme_estrategia', as: :destroy_pme_estrategia

  get 'plan-mejoramiento-educativo/get_pme_accion' => 'pme_accion#get_pme_accion', as: :get_pme_accion
  get 'plan-mejoramiento-educativo/sl_pme_accion' => 'pme_accion#sl_pme_accion', as: :sl_pme_accion
  get 'plan-mejoramiento-educativo/:est/acciones' => 'pme_accion#index', as: :pme_acciones
  get 'plan-mejoramiento-educativo/:est/nueva' => 'pme_accion#nueva', as: :pme_nueva_accion
  post 'plan-mejoramiento-educativo/:est/crear' => 'pme_accion#crear', as: :pme_crear_accion
  get 'plan-mejoramiento-educativo/:est/ver/:id/accion' => 'pme_accion#ver', as: :pme_ver_accion
  post 'plan-mejoramiento-educativo/:est/editar/:id/accion' => 'pme_accion#editar', as: :pme_editar_accion
  post 'plan-mejoramiento-educativo/:est/eliminar/:id/accion' => 'pme_accion#eliminar', as: :pme_eliminar_accion

  get 'plan-mejoramiento-educativo/:est/ver/:id/accion/:act/actividad' => 'pme_actividad#ver', as: :pme_ver_actividad
  get 'plan-mejoramiento-educativo/:est/ver/:id/pme_nueva_actividad' => 'pme_actividad#nueva', as: :pme_nueva_actividad
  post 'plan-mejoramiento-educativo/:id/crea_actividad' => 'pme_actividad#crear', as: :pme_crea_actividad
  post 'plan-mejoramiento-educativo/:id/actualiza_actividad' => 'pme_actividad#actualiza', as: :pme_actualiza_actividad
  post 'plan-mejoramiento-educativo/:id/subir_pme_actividad_doc' => 'pme_actividad#subir_pme_actividad_doc', as: :subir_pme_actividad_doc

  get 'opi/nueva' => 'opi#nueva', as: :nueva_opi
  post 'opi/crear' => 'opi#crear', as: :crear_opi
  get 'opi/validar' => 'opi#validar', as: :validar_opi
  get 'opi/:id/ver' => 'opi#ver', as: :ver_opi
  post 'opi/:id/actualizar' => 'opi#actualizar', as: :actualiza_opi

  get 'gestionar/:id/opi' => 'gestionar#opi', as: :gestionar_opi
  post 'gestionar/:id/validar' => 'gestionar#validar', as: :gestionar_validar_opi
  post 'gestionar/:id/sigue_conducto' => 'gestionar#sigue_conducto', as: :sigue_conducto
  post 'gestionar/:id/responde_consulta' => 'gestionar#responde_consulta', as: :responde_consulta
  post 'gestionar/:id/rechazada' => 'gestionar#rechazada', as: :gestionar_rechazada
  post 'gestionar/:id/adquisicion' => 'gestionar#adquisicion', as: :gestionar_adquisicion
  post 'gestionar/:id/termina_decreto' => 'gestionar#termina_decreto', as: :termina_decreto

  get 'xml/' => 'xml#index', as: :xml

  get 'bandejas/' => 'bandeja#index', as: :bandejas
  get 'bandejas/mi-bandeja' => 'bandeja#mi_bandeja', as: :mi_bandeja
  get 'bandejas/asesor_subvencion' => 'bandeja#asesor_subvencion', as: :entrantes_asesor_subvencion
  get 'bandejas/encargado_subvencion' => 'bandeja#encargado_subvencion', as: :entrantes_encargado_subvencion
  get 'bandejas/:id/entrantes' => 'bandeja#entrantes', as: :bandeja_entrantes
  post 'bandejas/guardar' => 'bandeja#guarda', as: :guarda_bandeja
  get 'bandejas/:id/ver' => 'bandeja#ver', as: :ver_bandeja
  post 'bandejas/:id/guarda_usuario' => 'bandeja#guarda_usuario', as: :guarda_usuario_bandeja
  post 'bandejas/:id/elimina_usuario' => 'bandeja#elimina_usuario', as: :elimina_usuario_bandeja

  get 'conducto/' => 'conducto#index', as: :conducto
  post 'conducto/guardar' => 'conducto#guardar', as: :guarda_conducto

  get 'encargados-subvencion/' => 'encargado#encargados', as: :encargados_subvencion
  get 'asesores-subvencion/' => 'encargado#asesores', as: :asesores_subvencion
  post 'encargados-subvencion/guarda_encargado' => 'encargado#guarda_encargado', as: :guarda_encargado
  post 'asesores-subvencion/guarda_asesor' => 'encargado#guarda_asesor', as: :guarda_asesor
  post 'encargados-subvencion/:id/borra_asesor' => 'encargado#borra_asesor', as: :borra_asesor
  post 'asesores-subvencion/:id/borra_encargado' => 'encargado#borra_encargado', as: :borra_encargado

  get 'cuentas_gastos/' => 'cuenta_gastos#index', as: :cuentas_gastos
  post 'cuentas_gastos/guardar' => 'cuenta_gastos#guardar', as: :guarda_cuenta_gasto
  post 'cuentas_gastos/eliminar' => 'cuenta_gastos#eliminar', as: :eliminar_cuenta_gasto

  get 'usuarios/' => 'usuarios#index', as: :usuarios
  get 'usuarios/nuevo' => 'usuarios#nuevo', as: :nuevo_usuario
  get 'usuarios/bajas' => 'usuarios#bajas', as: :bajas_usuario
  post 'usuarios/guardar' => 'usuarios#guardar', as: :guardar_usuario
  get 'usuarios/:id/editar' => 'usuarios#editar', as: :editar_usuario
  get 'usuarios/:id/perfil' => 'usuarios#perfil', as: :perfil
  post 'usuarios/:id/actualizar' => 'usuarios#actualizar', as: :actualizar_usuario
  post 'usuarios/:id/actualizar_perfil' => 'usuarios#actualizar_perfil', as: :actualizar_perfil
  post 'usuarios/:id/actualiza_password' => 'usuarios#actualiza_password', as: :actualiza_password

app/models/pme_actividad.rb
class PmeActividad

  include DataMapper::Resource
  include DataMapper::Timestamps

  property :id, Serial
  property :nombre, String, :required => true, :length => 200
  property :descripcion, Text, :required => true
  property :desde, Date, :required => true
  property :hasta, Date, :required => true
  property :responsable_nombre, String, :required => true, :length => 200
  property :es_vigente, Boolean, :required => true, :default => true
  property :terminado, Boolean, :required => true, :default => false
  property :avance, String

  timestamps :at 

  has n, :pme_actividad_docs
  belongs_to :pme_accion
  

end

app/controllers/pme_actividad_controller.rb
class PmeActividadController < ApplicationController


	def ver
    @est = Establecimiento.all(:hex_url => params[:est]).first
    @accion = PmeAccion.get params[:id]
    @dimension = @accion.pme_estrategia.pme_objetivo.pme_dimension_id
    @objetivo = @accion.pme_estrategia.pme_objetivo.id
 	@actividad = PmeActividad.get params[:act]

  end

  def nueva
    @est = Establecimiento.all(:hex_url => params[:est]).first
    @accion = PmeAccion.get params[:id]



  end

  def subir_pme_actividad_doc

  	documento = PmeActividadDoc.new params[:doc]
	documento.pme_actividad_id = params[:id]
	documento.departamento_id = @usuario_actual.departamento_id
	documento.usuario_id = @usuario_actual.id
	documento.save
  @actividad = PmeActividad.get params[:id]
  if @actividad.avance == "100"     
    @actividad.update terminado: true 
  end
	size = PmeActividadDoc.all(:pme_actividad_id => params[:id]).count + 1
	respond_to do |format|
   		format.html { 		
   			flash[:notificacion] = "exito."
			redirect_to :back
		}
   		format.json {
   			render :json => {
   				"estado" => "Exito",
   				"url" => documento.archivo.url,
   				"id" => documento.id,
   				"name" => documento.name,
   				"uploader" => "#{@usuario_actual.nombre} #{@usuario_actual.apaterno}",
   				"numero" => size,
   				"fecha" => documento.created_at.strftime("%d/%m/%Y %H:%M")

   			}
   		}
 	end
	rescue Exception => e
		puts "ERROR::::::: #{e.message} #{e.message.inspect}".red
		respond_to do |format|
	      format.html { 
	      	flash[:error] = "Verifique los datos ingresados"
	      	redirect_to :back
	      }
	      format.json {
   			render :json => {
   				"estado" => "Error #{e.message}"
   			}
   		}
	    end
  	
  end

  def actualiza
  		@actividad = PmeActividad.get params[:id]
		  @actividad.update params[:actividad]	

      if @actividad.avance == "100"   	
        if not @actividad.pme_actividad_docs.blank?
           @actividad.update terminado: true 
        end
      else
        @actividad.update terminado: false
      end
	

  	respond_to do |format|
            format.html {       
                flash[:notificacion] = "Se ha Guardado la actividad."
                redirect_to :back
            }
            format.json {
                render :json => {
                    "estado" => "Exito",
                    :id => @actividad.id

                }
            }
        end
        rescue Exception => e
            puts "ERROR:::: #{e.message.inspect}"
            puts "ERROR:::: #{e.backtrace}".red
            respond_to do |format|
              format.html { 
                flash[:error] = "Verifique los datos ingresados"
                redirect_to :back
              }
              format.json {
                render :json => {
                    "estado" => "Error: #{e.message}"
                }
            }
        end
  end


  	def crear
		@actividad = PmeActividad.new params[:actividad]
		@actividad.pme_accion_id = params[:id]	  	
		@actividad.avance = "0"  	
        @actividad.desde = params[:fechas].split(" - ").first
        @actividad.hasta = params[:fechas].split(" - ").last
		@actividad.save




  	respond_to do |format|
            format.html {       
                flash[:notificacion] = "Se ha Guardado la orden Accion."
                redirect_to pme_nueva_accion_path 
            }
            format.json {
                render :json => {
                    "estado" => "Exito",
                    :id => @actividad.id

                }
            }
        end
        rescue Exception => e
            puts "ERROR:::: #{e.message.inspect}"
            puts "ERROR:::: #{e.backtrace}".red
            respond_to do |format|
              format.html { 
                flash[:error] = "Verifique los datos ingresados"
                redirect_to pme_nueva_accion_path
              }
              format.json {
                render :json => {
                    "estado" => "Error: #{e.message}"
                }
            }
        end
  end


end

app/helpers/pme_actividad_helper.rb
module PmeActividadHelper
end

app/views/pme_actividad/nueva.html.erb
<div class="row">
	<div class="col-lg-12">
		<ol class="breadcrumb">
		<li><a href="<%= pme_acciones_path @est.hex_url, :col => @est.hex_url, :dimension => @accion.pme_estrategia.pme_objetivo.pme_dimension_id %>">PME</a></li>
			<li><span><a href="<%= pme_ver_accion_path @est.hex_url, @accion.id %>">Accion</a></span></li>
			<li class="active"><span>Actividad</span></li>
		</ol>
		<h1>PME - Nueva Actividad</h1>
	</div>
</div>

<form action="<%= pme_crea_actividad_path @accion.id %>" method="post" id="pme_accion_form">
<div class="row form-horizontal">
	<div class="col-lg-12">
		<div class="main-box">
			<header class="main-box-header clearfix">
				<h2>Ingresar</h2>
			</header>
			<div class="main-box-body clearfix">
			 	

                <div class="form-group">
					<label for="inputPassword1" class="col-lg-2 control-label">Acción</label>
					<div class="col-lg-10">
						<input type="text" maxlength="200" value="<%= @accion.nombre %>" class="form-control " readonly="">
					</div>
				</div>

				<div class="form-group">
					<label for="inputPassword1" class="col-lg-2 control-label">Descripción Acción</label>
					<div class="col-lg-10">
						<textarea class="form-control required" rows="3" readonly="" ><%= @accion.descripcion %></textarea> 
					</div>
				</div>
				<div class="form-group">
					<label for="inputPassword1" class="col-lg-2 control-label">Fechas Acción</label>
					<div class="col-lg-10">
						<div class="input-group">
							<input type="text" class="form-control" value="<%= fecha(@accion.desde) %> - <%= fecha(@accion.hasta) %>" placeholder="Desde..." readonly="">
							<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
						</div>
					</div>
				</div>
				<hr />
				<div class="form-group">
					<label for="inputPassword1" class="col-lg-2 control-label">Actividad</label>
					<div class="col-lg-10">
						<input type="text" maxlength="200" class="form-control required" name="actividad[nombre]" >
					</div>
				</div>

				<div class="form-group">
					<label for="inputPassword1" class="col-lg-2 control-label">Descripción Act.</label>
					<div class="col-lg-10">
						<textarea class="form-control required" name="actividad[descripcion]" rows="3" ></textarea> 
					</div>
				</div>
				<div class="form-group">
					<label for="inputPassword1" class="col-lg-2 control-label">Responsable</label>
					<div class="col-lg-10">
						<input type="text" maxlength="200" class="form-control required" name="actividad[responsable_nombre]" >
					</div>
				</div>

				<div class="form-group">
					<label for="inputPassword1" class="col-lg-2 control-label">Fechas Act.</label>
					<div class="col-lg-10">
						<div class="input-group">
							<input type="text" class="form-control  datepicker required" placeholder="Desde..." name="fechas">
							<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
						</div>
					</div>
				</div>

				
                <div class="form-group">
                    <div class="col-lg-12 text-center">
                        <button id="crear_btn" class="btn btn-primary"><i class="fa fa-filter"></i> Crear Actividad</button>
                    </div>
                </div>
				
			
			</div>
		</div>
	</div>
</div>
</form>

<script type="text/javascript">

function showRequest2(formData, jqForm, options) { 

	$("#crear_btn").prop('disabled', true);
	$("#crear_btn").html('Enviando...');
	var validator = $( "#pme_accion_form" ).validate();
	if(validator.form()){
		return true;
	}else{
		alertify.error("Error, Por favor compruebe los campos señalados.");
		$("#crear_btn").prop('disabled', false);
		$("#crear_btn").html('Crear Accion');	
		return false;

	}




} 

// Funcion despues de enviarse 
function showResponse2(responseText, statusText)  { 

  console.log(responseText);
  console.log(statusText);

  if(responseText.estado == "Exito"){

    
    alertify.alert("Se ha creado la actividad exitosamente", function(){
     document.location.href = "/plan-mejoramiento-educativo/<%= @usuario_actual.departamento.establecimiento.hex_url %>/ver/<%= @accion.id %>/accion/" + responseText.id + "/actividad"
  	});

   
  }else{
  $("#crear_btn").prop('disabled', false);
  $("#crear_btn").html('Crear Orden');
   alertify.error(responseText.estado);
	}
}


  $(document).ready(function() {

     //Opciones jquery.forms
    var options2 = { 
        beforeSubmit:  showRequest2,  // Funcion a ejecutar antes de enviarse
        success:       showResponse2,  //Funcion a ejecutar despues de enviarse
        dataType:  'json' //tipo de dato a devolver
      }; 


      $("#crear_btn").click(function() {
	      $('#pme_accion_form').ajaxSubmit(options2); 
      })        


       $('.datepicker').daterangepicker(
			{
			    locale: {
			      format: 'DD/MM/YYYY'
			    },
			    startDate: '01/03/<%= Time.now.year %>',
			    endDate: '05/04/<%= Time.now.year %>'
			});



   $("#dimension_sel").change(function(){
			if($(this).val() == ""){
				$("#sl_objetivo").html("<option value=''>Seleccione Objetivo</option>");
				$("#sl_objetivo").attr('disabled', true);
			}else{
				$.getJSON("<%= get_pme_objetivo_path %>", { id: $(this).val() }, function(data){
					if(data.mensaje == ""){
						$("#sl_objetivo").removeAttr("disabled");
						$("#sl_objetivo").html(data.opciones);
					}else{
						$("#sl_objetivo").html("<option value=''>Seleccione Objetivo</option>");
						$("#sl_objetivo").attr('disabled', true);
						alertify.alert(data.mensaje);
					}
					
				}) 
			} 
		})


   $("#sl_objetivo").change(function(){
		if($(this).val() == ""){
			$("#sl_estrategia").html("").prop('disabled', true);
		}else{
			if($(this).val() == "0"){
				$("#sl_estrategia").prop('disabled', false);
				$("#sl_estrategia").html("<option value=''></option><option value='0'>Nueva Estrategia</option>");
			}else{
				$("#nuevo_objetivo").hide("slow");
				$.getJSON("<%= get_pme_estrategia_path %>", { id: $(this).val() }, function(data){
					if(data.mensaje == ""){
						$("#sl_estrategia").prop('disabled', false);
						$("#sl_estrategia").html(data.opciones);
					}else{
						$("#sl_estrategia").html("<option value=''>Seleccione Objetivo</option>");
						$("#sl_estrategia").attr('disabled', true);
						alertify.alert(data.mensaje);
					}
				}) 
			}
		} 
	})

   $("#sl_estrategia").change(function(){
		if($(this).val() == "0"){
			$("#nueva_estrategia").show("slow");
		}else{
			$("#nueva_estrategia").hide("slow");
		}	 
	})



  })
</script>